AWSTemplateFormatVersion: 2010-09-09
Description: Template to create S3 bucket for Data Lake storage
Parameters:
  BucketName1: 
    Type: String
    Default: entergy-bdi-raw-dev
  BucketName2: 
    Type: String
    Default: entergy-bdi-dataquality-dev
  BucketName3: 
    Type: String
    Default: entergy-bdi-curated-dev
  BucketName4: 
    Type: String
    Default: entergy-bdi-datamart-dev
  BucketAccessControl:
    Type: String
    Default: Private
    Description: Default access configuration is Private
    
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName1,BucketName2,BucketName3,BucketName4 
      AccessControl: !Ref BucketAccessControl      
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref "AWS::StackName", "-Bucket"]]
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

